services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db_arquivos_virtuais'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
