name: desafio
services:
  app:
    image: douglasss/sistema-arquivo-virtual:1.0.0
    restart: unless-stopped
    depends_on:
     - postgres
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db_arquivos_virtuais'      
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db_arquivos_virtuais'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    deploy:
      resources:
          limits:
            cpus: 0.50
            memory: 128M
          reservations:
            cpus: 0.25
            memory: 128M
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: unless-stopped
    depends_on:
      - app    
